[[headers]]
	for = "/*"
	[headers.values]
		Permissions-Policy = "interest-cohort=()"

[[redirects]]
	from = "/authors/#greg-tarnoff"
	to = "/authors/#nat-tarnoff"

[[redirects]]
	from = "/posts/2017-08-26-a11y-and-other-numeronyms/"
	to = "/posts/a11y-and-other-numeronyms/"

[[redirects]]
	from = "/posts/2013-01-14-alt-text/"
	to = "/posts/alt-text/"

[[redirects]]
	from = "/posts/2021-03-23-myth-alternate-text-can-be-automated/"
	to = "/posts/alternate-text-and-automation/"

[[redirects]]
	from = "/posts/2020-05-13-aria-has-perfect-support/"
	to = "/posts/aria-has-perfect-support/"

[[redirects]]
	from = "/posts/2013-01-14-aria-landmark-roles/"
	to = "/posts/aria-landmark-roles/"

[[redirects]]
	from = "/posts/2019-02-15-creating-valid-and-accessible-links/"
	to = "/posts/creating-valid-and-accessible-links/"

[[redirects]]
	from = "/posts/2013-01-16-future-proof-your-accessibility/"
	to = "/posts/future-proof-your-accessibility/"

[[redirects]]
	from = "/posts/2014-05-15-getting-started-aria/"
	to = "/posts/getting-started-aria/"

[[redirects]]
	from = "/posts/2013-01-11-how-to-hide-content/"
	to = "/posts/how-to-hide-content/"

[[redirects]]
	from = "/posts/2017-12-29-macos-browser-keyboard-navigation/"
	to = "/posts/macos-browser-keyboard-navigation/"

[[redirects]]
	from = "/posts/2013-01-14-never-use-maximum-scale/"
	to = "/posts/never-use-maximum-scale/"

[[redirects]]
	from = "/posts/2013-01-25-never-remove-css-outlines/"
	to = "/posts/never-remove-css-outlines/"

[[redirects]]
	from = "/posts/2020-01-23-operating-system-and-browser-accessibility-display-modes/"
	to = "/posts/operating-system-and-browser-accessibility-display-modes/"

[[redirects]]
	from = "/posts/2016-01-07-placeholder-input-elements/"
	to = "/posts/placeholder-input-elements/"

[[redirects]]
	from = "/posts/2013-04-21-myth-screen-readers-dont-use-javascript"
	to = "/posts/people-who-use-screen-readers-dont-use-javascript/"

[[redirects]]
	from = "/posts/2017-12-29-macos-browser-keyboard-navigation/"
	to = "/posts/safari-keyboard-navigation/"

[[redirects]]
	from = "/posts/2013-05-11-skip-nav-links/"
	to = "/posts/posts/skip-nav-links/"

[[redirects]]
	from = "/posts/2020-02-05-text-resizing-in-ios-and-android/"
	to = "/posts/text-resizing-in-ios-and-android/"

[[redirects]]
	from = "/posts/posts/2013-05-15-understanding-vestibular-disorders/"
	to = "/posts/understanding-vestibular-disorders/"

[[redirects]]
	from = "/posts/2015-01-05-what-is-color-contrast/"
	to = "/posts/what-is-color-contrast/"
